
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: 'Install Terraform'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform validate
  displayName: 'Terraform Validate'

- script: terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve -var-file="terraform.tfvars"
  displayName: 'Terraform Apply'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
